#ifndef TP_2019_1C_GANK_MID_SEMAPHORES_H
#define TP_2019_1C_GANK_MID_SEMAPHORES_H

sem_t SEM_MEMTABLE;
sem_t SEM_TMP;
sem_t SEM_TMPC;
sem_t SEM_COMPACTACTION;
sem_t SEM_PARTITION;

#endif //TP_2019_1C_GANK_MID_SEMAPHORES_H
